# Generated by Django 4.2.11 on 2024-05-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_posting_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(
                default=1, help_text="Name of the hiring company", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="education",
            field=models.CharField(
                default=1, help_text="Education level required", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="job_level",
            field=models.CharField(
                default=1, help_text="Experience level required", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="milestones",
            field=models.IntegerField(
                default=1, help_text="Number of milestones for the job"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="work_hours",
            field=models.CharField(
                default=1, help_text="work hours required", max_length=100
            ),
            preserve_default=False,
        ),
    ]
