# Generated by Django 4.2.11 on 2024-05-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_posting_app",
            "0002_job_company_name_job_education_job_job_level_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone", models.IntegerField()),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="submissions/%Y/%m/%d/"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_posting_app.job",
                    ),
                ),
            ],
        ),
    ]
