# Generated by Django 4.2.11 on 2024-04-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                ("freelancer_id", models.AutoField(primary_key=True, serialize=False)),
                ("freelancer_name", models.CharField(max_length=255)),
                ("experience", models.IntegerField(help_text="Experience in years")),
                ("skills", models.TextField(help_text="List of skills")),
                (
                    "available",
                    models.BooleanField(
                        default=True, help_text="Availability for new projects"
                    ),
                ),
            ],
        ),
    ]
