# Generated by Django 4.2.11 on 2024-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis", name="rate", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysis",
            name="sentiment_score",
            field=models.FloatField(default=0.0),
        ),
    ]
